-- MySQL Script generated by MySQL Workbench
-- Wed Dec 14 10:30:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`` ;

CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `administrateur` VARCHAR(45) NOT NULL,
  `consultant` VARCHAR(45) NULL,
  `candidat` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`connexion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`connexion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`connexion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateur` VARCHAR(255) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`id`, `role_idrole`),
  INDEX `fk_connexion_role1_idx` (`role_idrole` ASC) VISIBLE,
  CONSTRAINT `fk_connexion_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `mydb`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`candidat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`candidat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photo` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(30) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `age` VARCHAR(10) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `code_postal` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `pays` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `cv` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `metier` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(50) NOT NULL,
  `dateInscription` DATE NOT NULL,
  `dateDisponibilite` DATE NOT NULL,
  `connexxion_id` INT NOT NULL,
  `candidat_id` INT NOT NULL,
  `candidat_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `candidat_id1`),
  INDEX `fk_candidat_connexxion_idx` (`connexxion_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidat_connexxion`
    FOREIGN KEY (`connexxion_id`)
    REFERENCES `mydb`.`connexion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entreprise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`entreprise` ;

CREATE TABLE IF NOT EXISTS `mydb`.`entreprise` (
  `identreprise` INT NOT NULL,
  `logo` VARCHAR(100) NULL,
  `nom_entreprise` VARCHAR(50) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `code_postal` VARCHAR(50) NOT NULL,
  `ville` VARCHAR(100) NOT NULL,
  `pays` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `numero_siret` VARCHAR(255) NOT NULL,
  `nombre_employes` INT NOT NULL,
  `dateInscription` DATE NOT NULL,
  `Domaine_idDomaine` INT NOT NULL,
  `offre_idoffre` INT NOT NULL,
  `offre_candidat_id` INT NOT NULL,
  `offre_candidat_candidat_id1` INT NOT NULL,
  `offre_Domaine_idDomaine` INT NOT NULL,
  PRIMARY KEY (`identreprise`, `Domaine_idDomaine`, `offre_idoffre`, `offre_candidat_id`, `offre_candidat_candidat_id1`, `offre_Domaine_idDomaine`))
ENGINE = InnoDB
COMMENT = '\n\n\n\n';


-- -----------------------------------------------------
-- Table `mydb`.`Domaine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Domaine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Domaine` (
  `idDomaine` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `entreprise_identreprise` INT NOT NULL,
  `entreprise_Domaine_idDomaine` INT NOT NULL,
  PRIMARY KEY (`idDomaine`, `entreprise_identreprise`, `entreprise_Domaine_idDomaine`),
  INDEX `fk_Domaine_entreprise1_idx` (`entreprise_identreprise` ASC, `entreprise_Domaine_idDomaine` ASC) VISIBLE,
  CONSTRAINT `fk_Domaine_entreprise1`
    FOREIGN KEY (`entreprise_identreprise` , `entreprise_Domaine_idDomaine`)
    REFERENCES `mydb`.`entreprise` (`identreprise` , `Domaine_idDomaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`offre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`offre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`offre` (
  `idoffre` INT NOT NULL AUTO_INCREMENT,
  `contrat` VARCHAR(50) NOT NULL,
  `condition_travail` VARCHAR(1000) NOT NULL,
  `avantages` VARCHAR(1000) NOT NULL,
  `poste` VARCHAR(50) NOT NULL,
  `localisation` VARCHAR(255) NOT NULL,
  `dateOffre` VARCHAR(20) NOT NULL,
  `date_fin_offre` VARCHAR(20) NOT NULL,
  `candidat_id` INT NOT NULL,
  `candidat_candidat_id1` INT NOT NULL,
  `Domaine_idDomaine` INT NOT NULL,
  `salaire` VARCHAR(45) NULL,
  `mission` VARCHAR(1000) NOT NULL,
  `profil_recherche` VARCHAR(1000) NOT NULL,
  `specialitees` VARCHAR(1000) CHARACTER SET 'cp1250' NOT NULL,
  `entreprise_identreprise` INT NOT NULL,
  `entreprise_Domaine_idDomaine` INT NOT NULL,
  `entreprise_offre_idoffre` INT NOT NULL,
  `entreprise_offre_candidat_id` INT NOT NULL,
  `entreprise_offre_candidat_candidat_id1` INT NOT NULL,
  `entreprise_offre_Domaine_idDomaine` INT NOT NULL,
  PRIMARY KEY (`idoffre`, `candidat_id`, `candidat_candidat_id1`, `Domaine_idDomaine`, `entreprise_identreprise`, `entreprise_Domaine_idDomaine`, `entreprise_offre_idoffre`, `entreprise_offre_candidat_id`, `entreprise_offre_candidat_candidat_id1`, `entreprise_offre_Domaine_idDomaine`),
  INDEX `fk_offre_Domaine1_idx` (`Domaine_idDomaine` ASC) VISIBLE,
  INDEX `fk_offre_entreprise1_idx` (`entreprise_identreprise` ASC, `entreprise_Domaine_idDomaine` ASC, `entreprise_offre_idoffre` ASC, `entreprise_offre_candidat_id` ASC, `entreprise_offre_candidat_candidat_id1` ASC, `entreprise_offre_Domaine_idDomaine` ASC) VISIBLE,
  CONSTRAINT `fk_offre_Domaine1`
    FOREIGN KEY (`Domaine_idDomaine`)
    REFERENCES `mydb`.`Domaine` (`idDomaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offre_entreprise1`
    FOREIGN KEY (`entreprise_identreprise` , `entreprise_Domaine_idDomaine` , `entreprise_offre_idoffre` , `entreprise_offre_candidat_id` , `entreprise_offre_candidat_candidat_id1` , `entreprise_offre_Domaine_idDomaine`)
    REFERENCES `mydb`.`entreprise` (`identreprise` , `Domaine_idDomaine` , `offre_idoffre` , `offre_candidat_id` , `offre_candidat_candidat_id1` , `offre_Domaine_idDomaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`candidature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`candidature` ;

CREATE TABLE IF NOT EXISTS `mydb`.`candidature` (
  `idcandidature` INT NOT NULL AUTO_INCREMENT,
  `candidat_id` INT NOT NULL,
  `candidat_candidat_id1` INT NOT NULL,
  `offre_idemploi` INT NOT NULL,
  `offre_candidat_id` INT NOT NULL,
  `offre_candidat_candidat_id1` INT NOT NULL,
  `offre_Domaine_idDomaine` INT NOT NULL,
  PRIMARY KEY (`idcandidature`, `candidat_id`, `candidat_candidat_id1`, `offre_idemploi`, `offre_candidat_id`, `offre_candidat_candidat_id1`, `offre_Domaine_idDomaine`),
  INDEX `fk_candidature_candidat1_idx` (`candidat_id` ASC, `candidat_candidat_id1` ASC) VISIBLE,
  INDEX `fk_candidature_offre1_idx` (`offre_idemploi` ASC, `offre_candidat_id` ASC, `offre_candidat_candidat_id1` ASC, `offre_Domaine_idDomaine` ASC) VISIBLE,
  CONSTRAINT `fk_candidature_candidat1`
    FOREIGN KEY (`candidat_id` , `candidat_candidat_id1`)
    REFERENCES `mydb`.`candidat` (`id` , `candidat_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidature_offre1`
    FOREIGN KEY (`offre_idemploi` , `offre_candidat_id` , `offre_candidat_candidat_id1` , `offre_Domaine_idDomaine`)
    REFERENCES `mydb`.`offre` (`idoffre` , `candidat_id` , `candidat_candidat_id1` , `Domaine_idDomaine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
